version: '3'

services:
  
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # # volume works as 
    # volumes:
    #   - ./db:/var/lib/mongodb
    command: mongod --bind_ip 0.0.0.0

  app:
    image: ansonwhc/eng110-micro-services:node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb://mongodb:27017/posts
    links:
      - mongodb
      
    # # this command will keep being run so the app won't run properly
    # command: node <app path>/seeds/seed.js
    # command: node seeds/seed.js

    # alternatively, in the terminal run: 
    #   $ docker exec -it container:id node seeds/seed.js
